/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.DepartmentDAO;
import Models.Department;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pazo
 */
public class DepartmentView extends javax.swing.JInternalFrame {

    /**
     * Creates new form DepartmentVieww
     */
    public DepartmentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Depname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Depno = new javax.swing.JTextField();
        Viewbutton = new javax.swing.JButton();
        SaveDepButton = new javax.swing.JButton();
        UpdateDepartmentButton = new javax.swing.JButton();
        DeleteDepartmentbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        deptable = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Department View");

        Depname.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Department No");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Department Name");

        Depno.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        Viewbutton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        Viewbutton.setText("View");
        Viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewbuttonActionPerformed(evt);
            }
        });

        SaveDepButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        SaveDepButton.setText("Save");
        SaveDepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDepButtonActionPerformed(evt);
            }
        });

        UpdateDepartmentButton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        UpdateDepartmentButton.setText("Update");
        UpdateDepartmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDepartmentButtonActionPerformed(evt);
            }
        });

        DeleteDepartmentbutton.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        DeleteDepartmentbutton.setText("Delete");
        DeleteDepartmentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDepartmentbuttonActionPerformed(evt);
            }
        });

        deptable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        deptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department No", "Department Name"
            }
        ));
        deptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(deptable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveDepButton)
                        .addGap(7, 7, 7)
                        .addComponent(UpdateDepartmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteDepartmentbutton)
                        .addGap(18, 18, 18)
                        .addComponent(Viewbutton))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(Depname)
                    .addComponent(Depno, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Depno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Depname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveDepButton)
                    .addComponent(UpdateDepartmentButton)
                    .addComponent(DeleteDepartmentbutton)
                    .addComponent(Viewbutton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void fillTable(){
    DepartmentDAO gDao = new DepartmentDAO();
    List<Department> departments = gDao.findAllDepartments();
    Object[] row = new Object[3];
    DefaultTableModel model = (DefaultTableModel)deptable.getModel();
    for(Department dep :departments){
        row[0] =  dep.getDepartmentNo();
        row[1] =  dep.getDepName();
        model.addRow(row);
    }
    }
    private void ViewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewbuttonActionPerformed
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_ViewbuttonActionPerformed

    private void SaveDepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDepButtonActionPerformed
        // TODO add your handling code here:

        Department d = new Department(Depno.getText(), Depname.getText());
        DepartmentDAO Ddao = new DepartmentDAO();
        Ddao.SaveDepartment(d);
        JOptionPane.showMessageDialog(null,"Department Saved Successfully!!!");
        Depname.setText("");
        Depno.setText("");
    }//GEN-LAST:event_SaveDepButtonActionPerformed

    private void UpdateDepartmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDepartmentButtonActionPerformed
        // TODO add your handling code here:
        Department d = new Department();
        DepartmentDAO Ddao = new DepartmentDAO();
        d.setDepName(Depname.getText());
        d.setDepartmentNo(Depno.getText());
        String msg = Ddao.UpdateDepartment(d);
        JOptionPane.showMessageDialog(null, d.getDepName()+ " " + msg);
        Depname.setText("");
        Depno.setText("");
        fillTable();
    }//GEN-LAST:event_UpdateDepartmentButtonActionPerformed

    private void DeleteDepartmentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDepartmentbuttonActionPerformed
        // TODO add your handling code here:
        Department d = new Department();
        DepartmentDAO Ddao = new DepartmentDAO();
        d.setDepName(Depname.getText());
        d.setDepartmentNo(Depno.getText());
        String msg = Ddao.DeleteDepartment(d);
        JOptionPane.showMessageDialog(null,d.getDepName()+ " " + msg);
        Depname.setText("");
        Depno.setText("");
        fillTable();
    }//GEN-LAST:event_DeleteDepartmentbuttonActionPerformed

    private void deptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deptableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) deptable.getModel();
        int rowSelect = deptable.getSelectedRow();
        Depno.setText(model.getValueAt(rowSelect, 0).toString());
        Depname.setText(model.getValueAt(rowSelect, 1).toString());
    }//GEN-LAST:event_deptableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteDepartmentbutton;
    private javax.swing.JTextField Depname;
    private javax.swing.JTextField Depno;
    private javax.swing.JButton SaveDepButton;
    private javax.swing.JButton UpdateDepartmentButton;
    private javax.swing.JButton Viewbutton;
    private javax.swing.JTable deptable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
